### PR TITLE
Unzip Dependency

### PR DESCRIPTION
**Pull request by amanharitsh123**
Unzip will be required to unzip the sugar activity packages

### CODE REVIEW

**Comment by Rishabh42** [comment]
It comes pre installed on Debian, so never had any problems with that. Thanks for adding it though, is it working fine on Ubuntu/schroot now?

**Comment by amanharitsh123** [comment]
Yes the script woked fine after installing unzip , but its better to add unzip as a dependency as the script undergo the whole build process and then fails at the end if unzip is not installed.

P.S : I didnt had unzip  preinstaled in schroot debian sctretch on ubuntu.

**Comment by Rishabh42** [comment]
That's good,and yes, unzip isn't pre-installed on schroot by default.

**Comment by Rishabh42** [comment]
But please make the required changes in the template files namely 'rpi2stretch-sugar' & 'rpi3stretch-sugar' instead of the default rpi23-gen-image.sh

**Comment by amanharitsh123** [comment]
How can i specify the script dependency there ? I suppose that the rpi2stretch-sugar template file contains the list of packages to be included in the  build image and not script dependencies . Please correct me if i am wrong

**Comment by Rishabh42** [comment]
The template files are used to add those specific settings/packages when executed with the rpi23-gen-image.sh, please also go through the previous commits and see if you can understand how the template files were created. You might realize how to make the changes then

**Comment by quozl** [comment]
Yes, unzip is not included in initial debootstrap of a debian stretch schroot, but is included if Sugar is installed.

It is the outer system that runs rpi23-gen-image that needs unzip, because 11-mod.sh does not enter the chroot to run unzip.

So add to both files templates/rpi{2,3}stretch-sugar;

```
REQUIRED_PACKAGES="${REQUIRED_PACKAGES} unzip"
```

But even so, this repository branched off upstream as of 14de7039 back in February 2017, and much has changed upstream, so please first rebase to upstream and resolve any consequent problems before correcting such comparatively trivial problems as packages missing from your schroot.

Of considerable merit upstream and yet to be merged are
* 6443586ab5b43cc105895b7fdcf9b29ecab0b653 add of APT_INCLUDES_LATE, into which the Sugar packages could be moved,
* 1e0652b25996ee27dba026b7c86cd6f60ebc8185 add Debian Buster support,
* e09e278fb2ce1075db77ae3e53ab59e7a098ad69 fix missing dbus-x11, which @Rishabh42 added to templates/rpi{2,3}stretch-sugar without knowing that it was an upstream problem,

**Pull request merged**
