### PR TITLE
Enabled fbturbo

### PR DESCRIPTION
**Pull request by Rishabh42**

### CODE REVIEW

**Comment by quozl** [comment]
I don't see why you would want this (you didn't say in the commit message), and you haven't included any test reports.  It looks like automaticity.

According to https://github.com/drtyhlpr/rpi23-gen-image and https://github.com/ssvb/xf86-video-fbturbo the driver only improves window moves and scrolling.

Sugar does not move windows (it is a full screen window manager), and does very little scrolling.

The window moves that would be important are in the Frame animation, when F6 is pressed.  This animation is so sluggish on Ubuntu that my Sugar packages remove them altogether.

The scrolling that would be important is in Browse, and it isn't clear whether WebKit2 API will take advantage of it.

So test reports should focus on these two features, and on one particular web page that must be scrolled.

You don't need to release a new image to make these tests; with care, the `42-turbo.sh` file can be run in a root shell on a Raspberry Pi.

**Review by quozl — CHANGES_REQUESTED** [review]
- [ ] inadequate commit message (no reason for change, no testing reports).

**Comment by Rishabh42** [comment]
Thanks for the review, my mentor @Hrishi1999 had suggested that we enable fbturbo as it would make the animations faster. I've tested this and the difference in animation speed is not much. Should I remove this feature and close this PR?

**Comment by Hrishi1999** [comment]
I meant to test with fbturbo, and to see how did it affect transitions. Did you test browse?

**Comment by Rishabh42** [comment]
Yes, I had tested Browse

**Comment by quozl** [comment]
Closing because you've pushed changes in af2ad03 that aren't related to the pull request.

I've no opinion whether fbturbo should be used or not; my point is that you didn't say so in the commit message why it was being enabled and what result was observed.

Performance testing of features like this should use a quantitative approach; how much time in milliseconds does it take to scroll a test page in Browse.  A simple method is to use a phone camera to film the scroll, with and without fbturbo, then compare the timing in a video editor.

**Comment by quozl** [comment]
I've deleted the gsoc-dev branch, please use a branch in your own repository, thanks.

**Pull request closed without merging**
