### PR TITLE
Audio Fix

### PR DESCRIPTION
**Pull request by amanharitsh123**
I have tested audio using speak activity  and it seems to work fine now 
Issue #4 
P.S : i was getting sound from HDMI

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Reviewed.

Commit message could be "Enable audio via HDMI"?

Should this be merged, we diverge from upstream in two _different_ ways;
* `bootstrap.d/11-mod.sh`, files named with nn-scope.sh, and
* `custom.d/audio_fix.sh`, files named with scope_fix.sh

My preference is to diverge in one way only.  Which way shall we use?

**Comment by amanharitsh123** [comment]
Both ways differ slightly ,after nn-scope.sh(In this case 11-mod.sh) there are several scripts which are executed before the image has been generated ,  but scripts in custom.d are executed just before the image creation . I didnt merged the audio_fix.sh script into 11-mod.sh because i was not confident that the changes might retain in boot/config.txt until the image creation.
If you  prefer only one way , then i will merge audio_fix.sh into 11-mod.sh and will do another round of testing .

**Comment by amanharitsh123** [comment]
@quozl Sir  Thanks for merging this PR , I Would also like to resolve other issues we cuurently have with this project. I am currently working on #7 . If you have any other issue in your mind , then please specify

**Comment by quozl** [comment]
I'm confused as to why you would hide this kind of discussion in the tail end of a merged pull request, but happy to answer if that's what you need.  A bit of history to help you see how I see;

* our [GSoC 2017 project ideas](https://wiki.sugarlabs.org/go/Summer_of_Code/2017) listed a "Sugar on Raspberry Pi", which said expected results were

    > An image for RPi,
    > which boots to a Sugar desktop environment, and
    > is suitable for inclusion on the RPi download page.

* @rishabh42 won the bid and [worked on the project](https://wiki.sugarlabs.org/go/Summer_of_Code/Rishabh_Thaney), and the result was an image which was nearly suitable, and this was good progress, but not as much as some of us had hoped.  Not a criticism of Rishabh; there were just a lot of other problems to fix.

* during the project, the Fedora SoaS image for Raspberry Pi 3 was tested, and found to be in much better and usable condition than the Debian build, so that's the build that Sugar Labs web site promotes for Raspberry Pi users, see [Rpi.md](https://github.com/sugarlabs/sugar/blob/master/docs/rpi.md).

* after the project, a new version of Raspbian was released, which includes Sugar as an option, see [Debian.md](https://github.com/sugarlabs/sugar/blob/master/docs/debian.md).

I'm personally happy with the Fedora SoaS image for Raspberry Pi 3.  Many of the bugs in both the Fedora and Debian builds of Sugar are because of missing-in-action activity maintainers, and nothing to do with build mechanisms.  So my focus is on activity maintainers at the moment.

As you're interested in our fork of rpi23-gen-image, you are welcome to work on whatever issues you like.  I've no preferences.

**Pull request merged**
