### PR TITLE
Synced with Upstream and removed dbus from template

### PR DESCRIPTION
**Pull request by amanharitsh123**

### CODE REVIEW

**Comment by quozl** [comment]
Bit more information would be helpful; does it build, does it boot, and does it work?

**Comment by amanharitsh123** [comment]
I will report all of this by next 12 hrs @quozl

**Comment by quozl** [comment]
I disagree with your proposal to merge upstream like this, because it makes a mess of the history; we might instead rebase;

* 14de70396904f0dc9fb65148735c94b5bcefc2d9 is our point of departure from upstream,
* https://github.com/sugarlabs/rpi23-gen-image/commit/f350e56bc3b2527838a381541b1853b91c8f0066 is the delta from upstream to this repository at the completion of the GSoC 2017 work; plus the dbus changes, and as you can see it is small and easy to understand,
* [2018-02-21-revert-upstream](https://github.com/sugarlabs/rpi23-gen-image/commits/2018-02-21-revert-upstream) branch is a revert of the GSoC 2017 work, followed by an uncomplicated merge with upstream, followed by reapplying the GSoC 2017 work.

**Comment by amanharitsh123** [comment]
I think you have already rebased this fork with the upstream here https://github.com/sugarlabs/rpi23-gen-image/commits/2018-02-21-revert-upstream
Should I close this PR? and test this rebased branch you have made

**Comment by quozl** [comment]
You might compare my rebased branch against your merged branch to see if I missed anything; if I didn't, then it doesn't matter which branch you test.  If there is a difference, you might try to figure out what it was caused by.  Let me know your results.

**Comment by amanharitsh123** [comment]
**Build Report:**
The build process gone smoothly without any errors and the image file was generated successfully .
I have booted the image and it works fine(automatic login works ). Tested some of its activities and i found no issue with them .
Rpi connected to wifi successfully .
**Issues :** 
1)Rpi got heated after 15 mins , I can sense the heat even above the case . I am using an open case (Transparent with heat sinks) (room temp 22C) 
I am using my rpi with kodi as well and its not get this much heated even in 1.5 hrs of usage .
2) No audio output 
**Difference between Your rebased branch and My PR:**
The only difference is template file, i have removed dbus from aptinclude
(Have tested this  build with my synced  repo)

@quozl Is there anything else you want me to test specifically or do you want any logs?

**Comment by quozl** [comment]
Thanks, I'll bring my branch into sugarlabs/master and we can both work from there.  Please push your tested branch to your repository and tell me the commit hash.

Some heating is normal, but please get some more data;

* log the values from the on-chip thermal sensor, see below,
* use `sudo vmstat 1 60` to capture some performance data, and drop into a gist or reply here; the most important column to watch is "cpu id" which means percentage of time the CPU is idle,
* see if the CPU idle value totally collapses to zero after you've started an activity; this represents an activity with a bug that does not process events properly,
* see if the Write activity causes this; it is a known problem with the AbiWord, see issue #9, and [Debian Bug #851052](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851052), making sure you have the fix to the bug in your system.
* see if Rasbian does the same amount of heating; with or without Sugar running in Raspbian.

Not surprised by audio problems; see #4 and check if it still matches in detail.

**Logging On-Chip Thermal Sensor**

* create a script /usr/local/bin/log-thermal containing

```
#!/bin/bash
TS=$(date --utc --rfc-3339=seconds)
echo $TS $(</sys/devices/virtual/thermal/thermal_zone0/temp)
```

* set the script executable

```
sudo chmod +x /usr/local/bin/log-thermal
```

* test the script once and confirm output looks sane

```
sudo /usr/local/bin/log-thermal
```

sample output

```
2018-02-21 19:32:51+00:00 50464
```

* add the script to crontab

```
sudo crontab -e
```

an editor will begin, add a line to the end of file

```
* * * * * /usr/local/bin/log-thermal >> /var/log/thermal.log
```

* verify that /var/log/thermal.log is growing at one line per minute,

**Comment by quozl** [comment]
Rebased master and deleted temporary discussion branches.

For the thermal problem, please open a new issue or reply here if there isn't a problem.

**Comment by amanharitsh123** [comment]
Commit Hash : e2b69b3b8b897d94ea05642d1037279bc863c8ec
Link:https://github.com/amanharitsh123/rpi23-gen-image/commit/e2b69b3b8b897d94ea05642d1037279bc863c8ec

**Comment by amanharitsh123** [comment]
Hash : https://github.com/amanharitsh123/rpi23-gen-image/commit/c2f65efa2c4bf3a2eca1aae4605f1c48da3b3f02
I will upload the test results for the above cases soon.

**Comment by amanharitsh123** [comment]
## Performance Record 
I have recorded the vmstat output , and added some relevant data in the Gist Description 
https://gist.github.com/amanharitsh123/a9bb146520bb026004da025e1b70d961
## Heating Issue
I was not able to take logs periodically using cron , maybe  I have done some mistake while configuring it, Although I have checked the temperature between my half hour of usage and the temperature rise was almost negligible .
**Reason For The Heating Issue Earlier :** Previously , In order to check the audio output I was browsing Youtube , which caused  high CPU usage for around 20mins. May be thats the reason behind Heating. 
I concluded this  by observing vmstat while browsing Youtube. 
## Write Activity
There is not any issue with the Cedit 
## CPU Idle Time 
I have tested all 23 activities , and CPU idle value doesnt collapses to zero with anyone .
## Audio Output
I have collected the lsmod output for both sugar(alsamixer not working ) and raspbian(alsamixer working well) 
Rapbian: https://gist.github.com/amanharitsh123/b71d08907ab0b2a3814dd7200589a7c5
Sugar : https://gist.github.com/amanharitsh123/85c055197ec91a26eec68d764ca187cf
The error is with the module snd_bcm2835  , it is disabled in case of rpi . Enabling it with modprobe might solve the issue (Havent tried it yet , but could be a solution):
`sudo apt-get install alsa-utils`
`sudo modprobe snd_bcm2835`
Resource : https://www.raspberrypi.org/forums/viewtopic.php?t=7663#p93439
## Other Observations
### Automatic Login 
The automatic login works everytime , even if we directly poweroff the rpi instead of shutdown. Looks like this bug has been fixed by some upstream improvements.
@quozl  Is there anything else that  i should test the image for?

**Comment by quozl** [comment]
Thanks, your https://github.com/amanharitsh123/rpi23-gen-image/commit/c2f65efa2c4bf3a2eca1aae4605f1c48da3b3f02 is slightly different to `sugarlabs/master`, but none of the changes pertain to the problems you've mentioned.  I'll leave it to you to manage your fork.

For the heating problem when Browse is used with YouTube; this is YouTube's decision, and you're running their JavaScript code, so who cares.

But if it happens after Browse tabs are closed, it may be related to a previous problem.  See https://github.com/sugarlabs/browse-activity/pull/18, https://github.com/sugarlabs/browse-activity/issues/36 and https://bugs.sugarlabs.org/ticket/4183 for history.  Can be tested by setting up an HTTP server with an automatic refresh page, then watching the server logs.

**Comment by amanharitsh123** [comment]
No , it doesnt happens after the browser tabs are closed , so i suppose that browsing youtube was the only reason for overheating

**Comment by quozl** [comment]
Thanks.  Certainly not our problem then.

For your interest and confidence in the hardware platform, I suggest you work and resolve your issues with running `/usr/local/bin/log-thermal` and see if it exceeds the maximum operating temperature of the Microchip LAN9512 chip; which is 70°C.  When it does so, USB and ethernet may begin to fail in some way.  It is best to keep the unit cooler if the load causes such temperatures.

**Pull request closed without merging**
